<Project Sdk="Microsoft.NET.Sdk">

	<Import Project="..\FMSC.VolumeLibrary.Test.Common\FMSC.VolumeLibrary.Test.Common.projitems" Label="Shared" />
	<Import Project="..\FMSC.VolumeLibrary.Test.Common\FMSC.VolumeLibrary.Test.Common.props" />

	<PropertyGroup>
		
		<Platform>AnyCPU</Platform>
	</PropertyGroup>

</Project>
